server.port: 8080

spring:
  application:
    name: noticeboard
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/db명?serverTimezone=UTC
    username: 계정
    password: 암호

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
      show-sql: true
      format_sql: true
      use_sql_comments: true

