server.port: 8080

logging:
  level:
    root: WARN
    org.springframework.web.reactive.function.client: trace
    org.hibernate.type.descriptor.sql: TRACE

spring:
  application:
    name: noticeboard
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/db명?serverTimezone=UTC
    username: 계정
    password: 암호

  jpa:
    database: mysql
    show-sql: true
    properties:
      hibernate:
        format_sql: true

